import Head from 'next/head'
import { Presentation } from '../components/app/base/presentation/Presentation'
import { motion, useScroll } from 'framer-motion'
import { WorkExeperience } from '../components/app/base/workExperience/WorkExeperience';
import { Skillset } from '../components/app/base/skillset/Skillset';

export default function Home() {
  const { scrollYProgress } = useScroll();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <motion.div style={{ scaleX: scrollYProgress }} />
        <motion.h1 animate={{ y: 100 }}>
          Wubba Lubba Dub Dub!
        </motion.h1>
        <Presentation />
        <WorkExeperience/>
        <Skillset/>
      </main>

    </>
  )
}
